# What is NumPy?
-> NumPy is a Python library used for working with arrays.

-> It also has functions for working in domain of linear algebra, fourier transform, and matrices.

-> NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

-> NumPy stands for Numerical Python.

## Why Use NumPy?
-> In Python we have lists that serve the purpose of arrays, but they are slow to process.

-> NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

-> The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

-> Arrays are very frequently used in data science, where speed and resources are very important.

In [15]:
# to install in vs use: pip install numpy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [16]:
a=[1,2,3,4]
b=[5,6,7,8]
c=a+b
print(c)


[1, 2, 3, 4, 5, 6, 7, 8]


In [18]:
a_array = np.array(a)
b_array = np.array(b)
c_array = a_array + b_array
print(c_array)

[ 6  8 10 12]


In [19]:
type(c_array)

numpy.ndarray

In [23]:
multi_dimension =[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
print(multi_dimension)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [24]:
print(np.array(multi_dimension))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
type(multi_dimension)

list

# zero and one() function and its use cases:

***These functions accept a shape argument (an integer for 1D or a tuple for multi-dimensional arrays) and an optional dtype argument to specify the data type, which defaults to float.


Syntax:
np.zeros(shape, dtype=float): Creates an array initialized to 0. 

np.ones(shape, dtype=float): Creates an array initialized to 1.


np.zeros() Use Cases: 
1. Placeholder Initialization: 
                Creating empty arrays to be filled later without memory garbage (safer than np.empty()).1
2. Zero-Padding: 
                Extending arrays (e.g., images or text sequences) to a uniform size by adding neutral borders.
3. Bias Initialization: 
                Setting neural network bias vectors to 0 before training.
4. Accumulators: 
                Initializing variables for summing values (e.g., total loss) to ensure a clean start.
5. Blank Canvases: 
                Creating black images (all pixel values 0) for drawing or masking operations.


np.ones() Use Cases
1. Bias Columns: 
                Generating a column of 1s to append to feature matrices for linear regression intercepts.
2. Multiplicative Identity: 
                Creating arrays for broadcasting where values must remain unchanged after multiplication.
3. Boolean Masks:
                Initializing masks where all elements are initially True (1) to be selectively turned False (0).
4. Scaling Factors: 
                Creating divisor or multiplier arrays that effectively act as "no-ops" in element-wise math until modified.
5. Default States: 
                Setting all elements of a state array to an "active" or "default" value of 1. 
***

In [28]:
#Example of zeros() and ones() function
data = np.zeros(5)
print(data)

[0. 0. 0. 0. 0.]


In [37]:
# Example-1: Use of zeros() function with one argument
# Create NumPy array using zeros() function
np_array = np.zeros(10)

# Print the data type of the array values
print("The data type of the array is: ", np_array)

The data type of the array is:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
mult_ones = np.ones((5,6))
mult_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
#creating two-dimesnsion using zeros() function
np_array1 = np.zeros((2,3), dtype=[('x','int'),('y','float')])
np_array1

array([[(0, 0.), (0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.), (0, 0.)]], dtype=[('x', '<i8'), ('y', '<f8')])

In [ ]:

# Create NumPy array using zeros() function
np_array = np.ones(5, dtype=int, order='F')

# Print the array values
print("The values of array are: \n", np_array)

# arange

np.arange() generates evenly spaced values within a defined interval, functioning as the NumPy equivalent of Python's built-in range() but returning an ndarray.  It supports integers, floats, and negative steps.

Syntax & Parameters
np.arange([start, ]stop, [step, ]dtype=None)

start (optional): Beginning of the interval (default: 0). 
stop: End of the interval (exclusive; the value is not included). 
step (optional): Spacing between values (default: 1).  Can be negative for descending sequences.
dtype (optional): Data type of the output array.


Use Cases:
1. Array Indexing:
           Creating integer sequences to slice or access specific elements in other arrays. 
2. Loop Iteration:
           Generating indices for for loops in vectorized operations where range() is insufficient.
3. Coordinate Generation:
           Creating 1D axes for mesh grids (np.meshgrid) in plotting and 3D computations.
4. Time Steps:
           Defining discrete time intervals for simulations or signal processing (e.g., np.arange(0, 10, 0.01)).

In [45]:


# Basic usage: 0 to 4
np.arange(5)
# Output: array([0, 1, 2, 3, 4])



  

array([0, 1, 2, 3, 4])

In [42]:
# Floats (use with caution regarding precision)
np.arange(0.0, 1.0, 0.2)
# Output: array([0. , 0.2, 0.4, 0.6, 0.8]) 

array([0. , 0.2, 0.4, 0.6, 0.8])

In [43]:
# With start and stop: 3 to 6
np.arange(3, 7)
# Output: array([3, 4, 5, 6])



array([3, 4, 5, 6])

In [44]:
# With step: 0 to 10, step 2
np.arange(0, 10, 2)
# Output: array([0, 2, 4, 6, 8])



array([0, 2, 4, 6, 8])

# Slicing in numpy

Slicing in NumPy extracts a range of elements using the syntax array[start:stop:step]  
Crucially, basic slicing returns a view (not a copy), 
meaning modifications to the slice directly affect the original array, saving memory. 

Syntax & Mechanics 
1. start: Inclusive beginning index (default: 0). 
2. stop: Exclusive ending index (default: end of array). 
3. step: Interval between elements (default: 1). Use negative values (e.g., ::-1) to reverse. 
4. Multi-dimensional: Separate slices for each axis with commas (e.g., array[row_slice, col_slice]).

Primary Use Cases
1. Memory-Efficient Subsetting: Extracting large segments of data (e.g., specific time windows in sensor data) without duplicating memory, as slices are views. 
2. Image Processing: Cropping regions of interest (ROI) by slicing height and width dimensions (e.g., image[50:200, 100:300]) or isolating color channels (image[:, :, 0]). 
3. Data Downsampling: Reducing dataset size for faster prototyping by selecting every n-th row (e.g., data[::10]). 
4. Train-Test Splitting: Quickly dividing datasets for machine learning by slicing rows (e.g., train = data[:800], test = data[800:]). 
5. Rolling Windows: Creating sliding windows for time-series analysis (e.g., calculating moving averages via data[i:i+window]). 

In [50]:
arr = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Basic Range
arr[1:10]      # [2, 3, 4]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:

# Step (Every 2nd element)
arr[::2]      # [0, 2, 4, 6, 8]



array([0, 2, 4, 6, 8])

In [52]:
# Reverse
arr[::-1]     # [9, 8, ..., 0]



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
# 2D Slicing (Rows 0-1, Col 1)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix[:2, 1] # [2, 5]

array([2, 5])

# Reshape and Ravel

##### np.reshape() changes an array's dimensions without altering data  

Function: Reconfigures the shape of an array (e.g., 1D to 2D) provided the total element count remains constant. 

Syntax: np.reshape(array, new_shape) or array.reshape(new_shape). 

Key Feature: Accepts -1 as a placeholder for one dimension, allowing NumPy to automatically infer the correct size. 

Memory: Returns a view if the data is contiguous; otherwise, it creates a copy. 

##### np.ravel() flattens an array to 1D
Function: Flattens any multi-dimensional array into a 1D array. 

Syntax: np.ravel(array) or array.ravel().

Key Feature: Faster than flatten() because it returns a view of the original data when memory layout allows. 

Memory: Modifying the raveled array affects the original if it is a view.  

##### Primary Use Cases
1. Deep Learning Input Preparation: Using reshape(-1, features) to flatten image tensors (e.g., 28x28 pixels) into feature vectors for fully connected layers. 
2. Batch Processing: Reshaping flat sensor data into (batch_size, time_steps, features) for RNNs or LSTMs. 
3. Memory-Efficient Flattening: Using ravel() instead of flatten() in large-scale data pipelines to avoid duplicating gigabytes of data when only read-access is needed. 
4. Matrix Operations: Reshaping 1D results back into 2D matrices for dot products or broadcasting alignment. 

In [56]:
num1=np.arange(1,61)
num1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [57]:
num1.reshape(10,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [62]:
matrix=num1.reshape(5,-1)  # row x column
matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [64]:
# Example of ravel()
one_D = np.ravel(matrix)
one_D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

# Broadcasting

Broadcasting is NumPy's mechanism for performing arithmetic operations on arrays of different shapes by automatically expanding the smaller array to match the larger one.  This allows for vectorized operations without physically copying data, ensuring high performance and memory efficiency.

### The Three Broadcasting Rules
NumPy determines compatibility by comparing array shapes element-wise, starting from the trailing (rightmost) dimension and moving left:
  
Rule of Broadcasting
1. all dimension of arrays must be equal
2. at least one shape of an array must be 1 or other must be equal
3. one whole array shape can be 1 x 1 for calculation

  
Rule 1 (Padding): If arrays have different numbers of dimensions, the shape of the one with fewer dimensions is padded with 1s on its leading (left) side.   
Rule 2 (Stretching): Two dimensions are compatible if they are equal or if one of them is 1.  The dimension with size 1 is "stretched" to match the other.  
Rule 3 (Error): If, in any dimension, the sizes disagree and neither is 1, a ValueError is raised (incompatible shapes).

In [65]:
num1=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]) #3 x 4


num2=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]) # 3 x 4

result = num1 + num2
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [68]:

row_vec = np.array([10, 20, 30, 40]) # Shape (4,)
# Step 1 (Padding): NumPy treats (4,) as (1, 4)
# Step 2 (Stretching): NumPy virtually replicates it 3 times to match (3, 4)
# Effectively: [[10, 20, 30, 40], [10, 20, 30, 40], [10, 20, 30, 40]]

result = num1 + row_vec
print(result)


[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [67]:
col_vec = np.array([
    [100],
    [200],
    [300]
])# Shape (3, 1)

# Step 1 (Stretching): NumPy virtually replicates the column 4 times to match (3, 4)
# Effectively: [[100, 100, 100, 100], [200, 200, 200, 200], [300, 300, 300, 300]]

result = num1 + col_vec
print(result)

[[101 102 103 104]
 [205 206 207 208]
 [309 310 311 312]]
